general {
    lock_cmd = pidof hyprlock || hyprlock # avoid starting multiple hyprlock instances
    before_sleep_cmd = loginctl lock-session # lock before suspend
    # Turn on display on wake up
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}

listener {
    timeout = 600
    on-timeout = loginctl lock-session
}
