# sample hyprlock.conf
# for more configuration options, refer https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock
#
# rendered text in all widgets supports pango markup (e.g. <b> or <i> tags)
# ref. https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#general-remarks
#
# shortcuts to clear password buffer: ESC, Ctrl+U, Ctrl+Backspace
#
# you can get started by copying this config to ~/.config/hypr/hyprlock.conf
#

$font = AtkynsonMono Nerd Font
$background = rgb(16161D)
$background_alt = rgb(223249)
$foreground = rgb(DCD7BA)
$muted = rgb(727169)
$accent = rgb(C0A36E)
$checking = rgb(7E9CD8)
$urgent = rgb(C34043)

general {
    hide_cursor = true
    ignore_empty_input = true
}

animations {
    enabled = false
}

background {
    monitor =
    path = 
    color = $background
}

# Helpful text
label {
    monitor =
    text = Session locked
    color = $muted
    font_size = 13
    font_family = $font

    position = 0, 45
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 22%, 3%
    outline_thickness = 2
    rounding = 3
    fade_on_empty = false

    inner_color = $background_alt
    outer_color = $accent
    check_color = $checking
    fail_color = $urgent
    font_color = $foreground
    font_family = $font

    placeholder_text = Password:
    fail_text = $PAMFAIL$FPRINTFAIL
    check_text = Authenticating...

    dots_text_format = *
    dots_size = 0.32
    dots_spacing = 0.22

    position = 0, -15
    halign = center
    valign = center
}

# Date
label {
    monitor =
    text = cmd[update:1000] date +"%Y-%m-%d %H:%M:%S %Z"
    color = $foreground
    font_size = 15
    font_family = $font

    position = -20, -16
    halign = right
    valign = top
}

# Keyboard Layout
label {
    monitor =
    text = $LAYOUT[en,ru]
    color = $muted
    font_size = 12
    font_family = $font
    onclick = hyprctl switchxkblayout all next

    position = -20, 16
    halign = right
    valign = bottom
}
