irssi.env: ENC[AES256_GCM,data:WTTvlKkRxLTtPjl7UmYZoSwOzJXZtsXHtED1,iv:15cCZip4tT+t7um6SeQHWsvmOkQQa8NVkqvLf+j/eKQ=,tag:FuJ2Q2NgSDjQjJ6+Qe4J3g==,type:str]
sops:
    lastmodified: "2026-07-09T20:40:16Z"
    mac: ENC[AES256_GCM,data:0/c1OUvknheC1NlIiS4JaEgJiQE4BXYdDTlGSHcaslO1EXdIrRW2w5Z0vTXp3gv9g9rX8rTnPCL59DSxZnSnUi/AzqVzLBBLp0hgoKZXD+M1z8irf+s5KNuIoxeSwuG9V8T02e/6Lla52V/G9HuphQuQwD1ya2s864788qym5go=,iv:4rb+RCY9ARVvD9EoWmOmnnRs6C7G8ygpmW/CfCao83c=,tag:ypbjjjtVu8NmSD6CUJhjbw==,type:str]
    pgp:
        - created_at: "2026-07-09T19:54:27Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DRF+a9RRKTfgSAQdA/V3m18kWGFWEf85yb16fvY+5dJOrx0aL54qP0d0Oen0w
            PkLZFgOhsdurxYQlPeG0heYd/u78T6lG+k5t4WsdML8Yqs78kyOxK+IIjdTX4lZa
            0lwBmggfyKL/OMo3fP7Z81V+VDBYbNDCbrCJ2oWyLyA02pCFCpE4jquis65W23vh
            akdn/dxIv30iUTKaiP1x79Z+LqtBQ7s7dQVMfqL4IawV/hMrNxgw7tGjNPatAQ==
            =gRyV
            -----END PGP MESSAGE-----
          fp: 91C72E117DF01124B6023EF8445F9AF5144A4DF8!
        - created_at: "2026-07-09T19:54:27Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dkcz7CjDeOEcSAQdAY9yZDY0G0sEhVLgvgkNSJW4c/Bb3Jdu61rik5i+wxlkw
            PKLkulkcSrts/wdlRdUlBcgS1iKYT57HdRu53j2XjcGRy8f5xABRoOauLFjZiAl5
            0lwBVJsqeCIxxf4NptLmc0w8ECQ1QbIJZW1PAAaGcrm0MQguAp5b5uYkJjdrfwPg
            3T4JgUSgvgCJgonI38JXitD638AlZ+MExe43BBnr6VDo8XdfPQeG+zmEctclCQ==
            =1bCi
            -----END PGP MESSAGE-----
          fp: 35B43EAA1688C1ECDB9157DB91CCFB0A30DE3847!
        - created_at: "2026-07-09T19:54:27Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DS2UfUs9F5iwSAQdAwH6eXjrw8tAbBvntHznvWps3q1MoSQlSpaL2wmSU82Qw
            U2ETHHt8Wc83VrjuHD/Vr75eAb/TPBKJBeRxc9AkCgBZ6fqpQGTkQrdgPWcEzdkJ
            0lwBpSOApJVq1XNeG41iU9+i4GlYtrOZLPEFPkF6xyPsRY5hntEqyO+l/4ACvqa/
            ifRUyUqfUXEwQYNQYrFUPAIJOoyHNLrN5yE+CUr2t0S2how6bZ0FVSPwyD2nhA==
            =kgMb
            -----END PGP MESSAGE-----
          fp: C457F736E3187E109CB4AE4E4B651F52CF45E62C!
        - created_at: "2026-07-09T19:54:27Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DE8BTihIXCBESAQdAvoBP5ZrowFwvmQpZX+3fz0NKHjgcEpN67nFVCtWYmXMw
            DGs39xVXMt7Qs63xzWBsF9aHO6EbDr/cKMqupci4/2gfG6oKedRuM5FW6JujoA8S
            0lwBfMwtf8RddyFEhaP2ezz2LSR8qrufQkBtvBvqEzf1xmA7l83w35BIwrJZUTew
            o3VyZhLO0AJ519zdsgSxNftBPH6CxLFjw8323cYU8fl6q0BbCqSMeVJRbNjy0w==
            =LLe2
            -----END PGP MESSAGE-----
          fp: 468F65CB69D97A9C5609A94913C0538A12170811!
        - created_at: "2026-07-09T19:54:27Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DDPkGui4gllMSAQdAxQce5Wkbo1pc8DKh/LpMFDFuejNfNYyXmbIIWrmPKWYw
            6dbPX7TNEiYWQ+QSxmsAwK/8iWWkh7BoYsnveYdTblREkWKX9N1UWgH3jupAMx6e
            0lwBSGMicDmx7jbSLoGcwDDfWNccKLwTbJM1n9HnHimK85fAX+ryiLfl4L8ypVZp
            80bahYbz6g3Ok1pFI/GxKoVEkBqASXnnrE8ZpEqNdsSYKlvj/zGYmKOmzC9OQw==
            =6Rzz
            -----END PGP MESSAGE-----
          fp: AE9A1DFB1B8541A01AAC4672042E55F6FA3635DD
    unencrypted_suffix: _unencrypted
    version: 3.13.1
