irssi.env: ENC[AES256_GCM,data:WTTvlKkRxLTtPjl7UmYZoSwOzJXZtsXHtED1,iv:15cCZip4tT+t7um6SeQHWsvmOkQQa8NVkqvLf+j/eKQ=,tag:FuJ2Q2NgSDjQjJ6+Qe4J3g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHJrNk9mYmxl
            dVJZUjRSdE5HRWVyWEdPSUdTUkU3dEFNTmUxcGVPTEdId0pKVjJZY1dHdS9ZRStD
            Qm9IeVdEenJsZXpxV2hQTFIzcDQzSGN6YTkxdDF6Z3RHa28yQ3RucktZTHphQ2t0
            U21Fd0VCaDljRFFqc0RZNmFPSm5NK3BTQmxCR2VDRktLaCsvQWEyVC9vazZmY1JP
            VE81Q0pjcERqMm9xWDB4c1ZKSStZN09KakpmcjZCSFdjcmx5ZlJRNENtU1RENnZY
            cGVjU1RGby9KNkZHejNkSkgwa0FRRWZONk5wa2dsSk96WDVrUXRTUHpYSlVVamJy
            Y0Y0a0dQcmZwTHRtRkhJcDNaQUYxbE1QNW54ZDc3S3pDMUNhOFBML21vY3FFNTM1
            eEdyU3UrT0dBdFdHL04yZ0FyU0syOExlRmYyYkZ3cUQxRzlJVkt1N2ZweWJVV2FF
            R0k1K25JSHpXVktWdDh0bFBrVUJRR00wcXQ2SFdyS1ltTjdIeHhsYXYvNXozMmNm
            aFBiN0FhM2tUK0xZMlB5TlR3eG1JN2llTktlZ3kxbzJSb2czRndiZXQyYnNyMUhQ
            c0pZa1R5c2EvZXVQY28xU3Naa3M3cThjek5nOU5HRWxhbkFFb2Y5blNQZEZaTjRz
            SHFsNzMvcFQzMVdVSmNsQ3EzekE1VHN3eFBhMHA3aVV5SGFPOWNsWHd5d2c3a015
            YWZxRW5saU4zdGxDKzNMOXRIUWd0ZVBEL242dGZpMkt3OTVFM0hsRmNLTTMxTnZj
            SVY4UUdoR1ZKdEk3cnNRZHBvVXpRdlMxeGp4d2M1cGptQnVSdStFVGV6bGF5TFJR
            Q3FQcUMreUJrQiswYmhzRUc2dndLbm13VG5TcmZHN2JtK242SVcvRW9HQ2k2RC82
            SWF0NUZta3cvZERPV1ZuY2pvRGYwaEdRSGZNMnFOUWg0M09XN1ZnU3RrZEJYancw
            UTMwTlhoeHQ5UnVxWFM3V1ZCQnVDdnE5RGx3Q2xEd2k4NGc0L3JQTTc0YWh1VnY3
            bjlwZW5OZFFDeWtHNWJvb2E3ZVNKMjV5aXJZZk1SOUFvb0xUejRWWmI1amN5aXpt
            VVZVYy9LQk9WWTN6ZkJ2bVVUK21CQWVWeGlBUlFXYVdaazAvQ3dKUktvM1VMazhp
            cVl1eWRSWVVrY0VrTHZkcUVLVFAzS1NWYlFGMW5sWlNDU0RUVFUyekRsTmd3VXZE
            ak5XWlJRN1VnVmNadU1VUTR6SEZ4OC84QjliaUNGWWJ6NWdCZUQ3UWhNdWlNVzMw
            MFphbEtCMi9KSDRKVjFHdnNPeUVheTh4QXJ1bmhNSEJmRTJOL1B6RVNqT0pDWDRT
            amRTdHE1KytxOEozLzBCbmVrY2ZlZkViMGl1SWlERzBOd2h4VlUrd2ZHYy9UT1lz
            dGlxRDBrWTZaVGhYb21tclVleldweHRIMjl1V215QUdLbVU2N002TW1HWGdHd2R4
            WjhMdHB1bHU5V05hOXFWby9wdDNrU1NnLzRzdXBGd3U5YjJQVHZUdDN3Y2p3WTMw
            bGord0NBb0VQcStRN283QUZybmxWUmIwdFNrSlpmS09DTTZ2azd3ZDgrMG1DS052
            YXdNYWlaRlZjKzRtODNGbTljdnFDOHFuMlJwR2xoNlNHSG5HcHhHcUJ2cUJlVjJa
            K2Z2UFhwdVkxeElUQ0UxcEVzME1TVHZtamJsVkdKcDZ3TVJLbTVhc2NSa3FnZUhi
            Z1lQSHc2ZFRIbFRSQnpUTUM0alkralIxTkNiUFFXV3R2SU9mNUhKS09mOGhWZEU3
            ZWV6dFViSm1NalNpK0RsQ3V5UXBSVkM0WlVvbEUrWDN0YzYrUkNaQlNBbnFwV1FV
            MHQ2VFRvT2RlVWg4aUpXWFRXZlpUcE5tUm5QbDdQOGNkWkpJOHMrTEJVVmowdUND
            b1lDaVVzWVNkazdCSDJWdzZOTGc1Tk0xRzBwc295WmpDSExIM05GYit6Z0hDQQpZ
            YkVFSGtkREJ6S05GeFlLTWh2VlZFckp1UXArVUliUkpES3NoOEpVdlI4Ci0tLSBu
            ZExrb3orKzhRRHYyb3BHTkRVaHFuNWt3M2hjV3ZEQjZCUjRGNFNzcThzCpYf7R7K
            9GbchQSdN4Z2Fnhu7CDnMX8qaHUvP2xZwXBlWwqJLjlRuAWeS5KIotwmtmDgS5MV
            nIX0h/lV3b7xnIQ=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq1rttu7ke45h4zq6j3f28rfkm79fate4kvq60v5m4mtvgnhv4xsx2he7992xd603uumf8e42dutwf5kunvqqq4zfmess6qv67dq8jfq5qp05eqxlrv6kshpzcvg2gfnljyqah3n9ul9zjcp5v8qamgsk2gsum4dpch99vxngf6lpqu0muvzetkr20gtnr3jyvtnrzuuesnf78qjttwdz86mjv9yud6rnd6nmvwweqlldjhrujuw26gatn5fdc45zaghp20sv2fary8285ngxe72hfkhx3hgesrew43838e3tjkz2mx0q3dgagv3n3r7w6r8ltvkdwhwsqdq66d58uupxt4erxagfc3w7rlcj63vzuveju3yasurwtn0ye2dx3qwwkzwmrq525rs6elmp29k5gdlhjkmnjzwqxges7mx47t39rr653ve9a52xhjz8k7gd39f92j8m6hsrlxw8dy33lrnvqtghqrgf4544t84ad8jqkwyp38w2eavsjm9jz38dscsh9wwcpde7f4dgecvql22fagj7aupz7jaw2q6k2zx47st4sgdqn3g9uhkka8whskmjwn5p67jh2v0p0mjtrq48tz8xxejznlhyhzr3lydkkza8dx6fvz4t27yyeeqq6265x8jpx9mw49r9f5trj59362vc99w7fykmmzd0a3q0fewaws3xrzhnwxaksuj077qw9zlqemt92ne6j8vnjc9wxzvg9ke3h34w2p7tyzlaxn34lkqhsnskff329xzuv4ewskvenxwk77uqp2f2z8svefn39v47skp968fq65tfutkrsuej43xvhg3vef3qzzm43755dswllm5292jvtd24xf47zxstzz6mtphnm5sznysasuw6yzhgfe6e48k4czwh08u6wh6u354h236lat9ppdrpr8xxts69z4yasttjufjsj6gwd37u8gmz4wrlj5gdhfnlzvzsqdhg7zr35tlrxqlme8c8mtp07e0j2ysyfgn7acvack4sjyku44m8r8kxz2fpy59yrk0n9qwynvjkxrwy92gf69mjskqk0unfc59q2jyfey9yy89y34xd53gp70mvf60xgxwresj4p23dyh0ggpxscr4p96typ4kkur0p3849586yy737sf2ad60s2gx4zs5egpwxh6ktx09mpxyrstnzjm030hy2zv2ksl3uq57fltshxsg506ey4dyevzp5nvgx39h8d656srfgpyy3g4azruf8ykz4dlrz5zcwhc62zvwlz5hfgjr7dr4s9n2nrkvurajzdnm9j99efep8m4q0z4kyn8kre80j0md9lx5v2le8y23c28kud94twpsdqx025ms7md8sefvszf74ue05lsy4ugcxh97gcm2rngqw4ezf92xykak368qcz32jmtxt9k5dqyexc5v3mpymz6e86n9pyxwdjqkrnrkf2ctpslq533un3qgsus8yjlrf58d7p6pu4kunwxe9gy9s83ssda4y7dtq4x6nl8vqckkl48jkgppzc7kcm4akq98u74ky5e59eydk4rfmzhe8wvdnz2dnz9qwhev5d2lka2kczk0v0rgdc7z6a5w33ge3ut9vsxrej3klpujzv4jaatk0jvw5p8vnwdzn3awq52vuqe0xju9nfn2nl85lw36f7vwc4xpxf3rgdu3rtttr5xqjnkzquz3aj2nhrkrruffz79uaetdq9gswev0glfvyex88c5ckqxs9vxplautymehl0lj90ef9vzhj3k2lqvkgyyhnjngaqcxfhepextjwcz6xp6ns3eqsqvjc2cd0yyl8fpyfn82ms2k2208q2y4q99py00a5q08uqaare6gu74l4pyz7886e229t9ssx50ltjq3s4nfwj5kuqta7j8u4kv8nu44dmljq7fff2llyptfyxlxq97xpenfssuwc4l
    lastmodified: "2026-07-09T20:40:16Z"
    mac: ENC[AES256_GCM,data:0/c1OUvknheC1NlIiS4JaEgJiQE4BXYdDTlGSHcaslO1EXdIrRW2w5Z0vTXp3gv9g9rX8rTnPCL59DSxZnSnUi/AzqVzLBBLp0hgoKZXD+M1z8irf+s5KNuIoxeSwuG9V8T02e/6Lla52V/G9HuphQuQwD1ya2s864788qym5go=,iv:4rb+RCY9ARVvD9EoWmOmnnRs6C7G8ygpmW/CfCao83c=,tag:ypbjjjtVu8NmSD6CUJhjbw==,type:str]
    pgp:
        - created_at: "2026-07-14T13:04:01Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DRF+a9RRKTfgSAQdAyR/R6k6S7VI5II+W6Im85Dz8safHbizOkWvEHvu9cFkw
            lqJkBUDIEz9u1lr9lIt67xPGhU7GqtTFRBukf9sqCJsu7PttZQwqSUwcHOg7xfbS
            0lwBxuIf/MA70vnPcAAFoGNwa0wR9/+hkVvmDoluePyvpTGrGgpHrrGf0qAc1Ffp
            s0yyh/NQYLYyfOjf1sMY5ebERMZY6YxNVn4S4DVNKLd342nQAS3gsV9ZMkhHpQ==
            =eGwu
            -----END PGP MESSAGE-----
          fp: 91C72E117DF01124B6023EF8445F9AF5144A4DF8!
        - created_at: "2026-07-14T13:04:01Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dkcz7CjDeOEcSAQdA5jyyH0TglqmrdFX18dPLkSsvMvRk/ZJrTtwNv8sta0ow
            reuPwpJs4+KAXM4uKx4d5JIzeXzPtu2XxxYoyCYcN6yOMAj3SipxczNV5qkhfQfm
            0lwB/O145RUX8XVc7d73tMwUbPcSS2BaKlaIuI6cXhwjoIQDo4nhwaDa2/HfuEeB
            b7ZdD/oudFJ/gFs65Ph4rF6vKkd2R3/fDGv8zYbY7Sftp7P/PMmuTGwzWOv3dA==
            =1SWt
            -----END PGP MESSAGE-----
          fp: 35B43EAA1688C1ECDB9157DB91CCFB0A30DE3847!
        - created_at: "2026-07-14T13:04:01Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DS2UfUs9F5iwSAQdA59JQGP4ZD9ff1nRqhXIVUBZv1locd3i6lbMMj4XTMl0w
            SmHi31kZXplHpELwYhmsD6yF4uj8lljb5m+cW7w3jGH8mmmVGhtm3d41gg0ZqL6d
            0lwBj9coLhkL5R78OjRMGqZvdKnh+19dul0y329V0FqGl8iFpzGWxxrTGkLTc+8+
            kpM1nOZjIl77xeEj862gH0i/tFPp97SY5MUzcP8N02rxBoLR0N1BUt2IfeBhjA==
            =pefZ
            -----END PGP MESSAGE-----
          fp: C457F736E3187E109CB4AE4E4B651F52CF45E62C!
        - created_at: "2026-07-14T13:04:01Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DE8BTihIXCBESAQdACbusBydbtxzQoSkDbx1d05Ko7ou22WHG9SDxNKo0flQw
            NpidoQcvE1NR+sNzlNAxLP0wMUK2S7af3jTu/f03SsPoew9MMzPTtbhHTwKw3VH4
            0lwB+aAfMjLphj3xrTkYRDP367LE9cwvu+dMX5W89Bcwl4Mp/BobWGwYOAi4yAfA
            yTyQbktlgplRDu2cTYppplSzJv05E1TVDQAmUnQKCKUpMDYJatgWAUSgdy4jVg==
            =q30R
            -----END PGP MESSAGE-----
          fp: 468F65CB69D97A9C5609A94913C0538A12170811!
        - created_at: "2026-07-14T13:04:01Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DDPkGui4gllMSAQdAX1kQGiwXRX/D8s7JWPNyxsGuVA4wiekmUHm/WTb212Uw
            l2iMhg4VdSFctxQSibVD9gT8U3pk5Jgn7bV4WrN3RPZzBFLYizj1vvlmSWXxS/jI
            0lwBtO9NvjYhJhnEnPglubHGTmfeMLkoR8lBVxdzY5Mm+9cKmQw1/79fZU91L6W7
            NkYi4pwO8ZwnsH98IR/fjehGAllw9E70gjwDRCQ1oBZ53oZYpOfBCJrobW9TqQ==
            =iyP4
            -----END PGP MESSAGE-----
          fp: AE9A1DFB1B8541A01AAC4672042E55F6FA3635DD
    unencrypted_suffix: _unencrypted
    version: 3.13.1
